const P=(vendor,name,model,type,form,desc,keys,scene,os='—',aliases='')=>({vendor,name,model,type,form,desc,keys,scene,os,aliases});
const products=[
P('华为','园区交换机','CloudEngine S8700 / S6700 / S5735-L','交换机','硬件','覆盖园区核心、汇聚和接入的以太网交换机系列。',['园区网络','堆叠','VXLAN','Telemetry'],'大中型园区、校园、分支','VRP','Huawei CE S系列'),P('华为','数据中心交换机','CloudEngine 16800 / 12800 / 8800','交换机','硬件','面向数据中心核心、Spine与Leaf架构的高密交换平台。',['数据中心网络','EVPN-VXLAN','RoCE','智能运维'],'云数据中心、AI网络、算力集群','VRP'),P('华为','企业路由器','NetEngine AR / NetEngine 8000','路由器','硬件','企业分支接入到广域骨干的路由器系列。',['SD-WAN','MPLS','SRv6','VPN'],'分支互联、广域网、运营商承载','VRP'),P('华为','下一代防火墙','HiSecEngine USG6000F / USG12000','安全','硬件+软件','融合访问控制、入侵防御、恶意流量检测等能力。',['NGFW','IPS','威胁情报','零信任'],'互联网出口、数据中心边界、园区边界','—'),P('华为','全闪存存储','OceanStor Dorado 2000 / 5000 / 8000','存储','硬件+软件','面向核心业务的企业级全闪存存储系列。',['全闪存','双活','NVMe','数据缩减'],'数据库、虚拟化、核心交易','OceanStor OS'),P('华为','融合存储','OceanStor 2600 / 5000 / 6800','存储','硬件+软件','兼顾块、文件等业务的企业级存储平台。',['SAN','NAS','快照','复制'],'通用数据中心、文件共享、备份','OceanStor OS'),P('华为','机架服务器','FusionServer Pro 2288H / 2488H','服务器','硬件','通用双路与多路机架服务器系列。',['鲲鹏/英特尔','PCIe扩展','RAID','iBMC'],'虚拟化、数据库、通用计算','iBMC'),P('华为','虚拟化与云平台','FusionCompute / 华为云Stack','云平台','软件','企业虚拟化与本地部署云平台产品线。',['虚拟化','IaaS','混合云','云管'],'私有云、政企云、数据中心云化','—'),
P('新华三 H3C','核心交换机','S12500R / S10500X','交换机','硬件','面向园区与数据中心核心的高端交换机系列。',['核心交换','IRF','EVPN','MPLS'],'数据中心核心、园区核心','Comware','华三 新华三'),P('新华三 H3C','园区交换机','S7500X / S6520X / S5130S','交换机','硬件','覆盖核心、汇聚、接入的园区交换产品族。',['IRF','PoE','VXLAN','可视化运维'],'园区网、校园网、分支','Comware','华三 新华三'),P('新华三 H3C','企业路由器','SR8800-X / MSR5600 / MSR3600','路由器','硬件','覆盖核心、汇聚与分支的多业务路由平台。',['MPLS','VPN','SD-WAN','SRv6'],'广域网、分支、出口','Comware','华三'),P('新华三 H3C','防火墙','SecPath M9000 / F5000 / F1000','安全','硬件+软件','从高端数据中心到园区边界的防火墙系列。',['NGFW','IPS','应用识别','安全策略'],'数据中心、互联网出口、分支','Comware'),P('新华三 H3C','无线接入点','WA6000 / WA7000 系列','无线','硬件','覆盖 Wi-Fi 6/7 场景的企业级无线接入点。',['Wi-Fi 6','Wi-Fi 7','漫游','射频优化'],'办公、教育、医疗、场馆','Comware'),P('新华三 H3C','机架服务器','UniServer R4900 G7 / R4700 G5','服务器','硬件','面向通用计算、HPC与AI扩展的机架服务器。',['双路服务器','GPU扩展','液冷','HDM'],'通用计算、AI、云桌面','HDM'),P('新华三 H3C','企业存储','Alletra MP / UniStor X10000','存储','硬件+软件','覆盖全闪、分布式和非结构化数据的存储产品线。',['全闪存','分布式','NVMe','数据服务'],'核心数据库、云、海量文件','—'),P('新华三 H3C','云平台','CloudOS / UIS 超融合','云平台','软件+一体机','云管理平台与超融合基础设施产品。',['IaaS','Kubernetes','超融合','多云管理'],'私有云、混合云、边缘云','—'),
P('深信服','下一代防火墙','AF 系列','安全','硬件+云服务','以本地引擎、AI和云端威胁情报构建边界防护。',['AI-Inline','NGFW','IPS','威胁情报'],'互联网出口、数据中心边界','—'),P('深信服','上网行为管理','AC 系列','安全','硬件+软件','提供应用识别、流量管理、访问控制和行为审计。',['应用识别','流控','审计','准入'],'园区出口、办公网、无线网络','—'),P('深信服','应用交付','AD 系列','网络应用','硬件+软件','面向关键业务的负载均衡、链路优化与高可用。',['负载均衡','GSLB','链路优化','SSL卸载'],'应用发布、多数据中心','—'),P('深信服','超融合基础设施','HCI / aCloud','超融合','软件+一体机','融合计算、存储、网络与安全的云基础设施。',['虚拟化','分布式存储','超融合','内建安全'],'数据中心整合、私有云、信创','aSV/aSAN'),P('深信服','企业级分布式存储','EDS','存储','软件+一体机','覆盖块、文件、对象场景的分布式存储。',['块存储','文件存储','对象存储','横向扩展'],'虚拟化、备份、海量非结构化数据','—'),P('深信服','桌面云','aDesk / VDS','云桌面','软件+终端','集中交付和管理虚拟桌面的数字办公平台。',['VDI','桌面协议','数据不落地','集中运维'],'办公、研发、教学、窗口终端','—'),P('深信服','统一端点安全','aES','安全','软件','融合终端防护、检测响应和统一管理。',['EPP','EDR','勒索防护','端网协同'],'PC、服务器、终端安全运营','—'),P('深信服','安全访问服务','SASE / 零信任','安全','云服务+软件','融合组网、访问控制和云化安全服务。',['SASE','SD-WAN','ZTNA','持续评估'],'分支、移动办公、第三方访问','—'),
P('锐捷网络','核心交换机','RG-N18000-X / RG-S7800C','交换机','硬件','面向数据中心和园区核心的高性能交换平台。',['核心交换','VSU','EVPN','Telemetry'],'数据中心、园区核心','RGOS'),P('锐捷网络','园区交换机','RG-S6000 / RG-S5000 / RG-S2900','交换机','硬件','覆盖汇聚与接入的园区交换机系列。',['PoE','VSU','云管理','极简网络'],'校园、办公、商业连锁','RGOS'),P('锐捷网络','企业无线','RG-AP / RG-WS 系列','无线','硬件+软件','企业级无线 AP 与控制器产品族。',['Wi-Fi 6/7','零漫游','WIS','云管理'],'教育、医疗、制造、办公','RGOS'),P('锐捷网络','企业路由器','RG-RSR / RG-EG 系列','路由器','硬件','覆盖广域互联、分支出口与综合网关场景。',['SD-WAN','VPN','流控','出口网关'],'分支、校园、企业出口','RGOS'),P('锐捷网络','云桌面','RG-CS / RG-CDC','云桌面','软件+终端','面向教学与办公的云桌面解决方案。',['VDI','IDV','终端管理','镜像管理'],'机房教学、办公桌面','—'),
P('中兴通讯','数据中心交换机','ZXR10 9900X / 5960 系列','交换机','硬件','面向数据中心核心与Leaf的交换机系列。',['EVPN-VXLAN','SRv6','Telemetry','高密端口'],'运营商云、政企数据中心','ZXROS'),P('中兴通讯','路由器','ZXR10 M6000 / ZSR 系列','路由器','硬件','覆盖运营商骨干与政企广域场景的路由产品。',['MPLS','SRv6','VPN','网络切片'],'骨干网、城域网、企业广域','ZXROS'),P('中兴通讯','服务器','R5300 G5 / R5500 G5','服务器','硬件','通用机架式服务器和算力平台系列。',['通用计算','GPU','高密度','带外管理'],'云计算、AI、数据库','—'),P('中兴通讯','分布式数据库','GoldenDB','数据库','软件','面向金融级核心场景的分布式数据库。',['分布式事务','高可用','在线扩展','金融核心'],'银行核心、交易系统','—'),
P('浪潮信息','机架服务器','NF5180M7 / NF5280M7','服务器','硬件','通用双路机架服务器代表系列。',['通用计算','PCIe','GPU扩展','BMC'],'虚拟化、数据库、企业应用','—'),P('浪潮信息','AI服务器','NF5688M7 / NF5468M7','AI算力','硬件','面向大模型训练与推理的多加速卡服务器。',['GPU','大模型','高速互联','液冷'],'AI训练、推理、HPC','—'),P('浪潮信息','存储','AS13000 / HF 系列','存储','硬件+软件','覆盖分布式存储与集中式全闪存储。',['分布式文件','对象存储','全闪存','数据保护'],'AI数据、云、核心业务','—'),P('浪潮信息','超融合','InCloud Rail','超融合','软件+一体机','融合计算、存储与云管的超融合基础设施。',['虚拟化','分布式存储','一体化运维','云管'],'私有云、分支云、数据中心','—'),
P('联想','机架服务器','ThinkSystem SR650 V3 / SR630 V3','服务器','硬件','企业级通用双路机架服务器系列。',['通用计算','内存扩展','GPU','XClarity'],'数据库、虚拟化、HPC','XClarity'),P('联想','存储','ThinkSystem DM / DE 系列','存储','硬件+软件','覆盖统一存储与高性能块存储的企业存储系列。',['SAN','NAS','全闪存','混合闪存'],'数据库、虚拟化、备份','—'),P('联想','边缘服务器','ThinkEdge SE450 / SE350','服务器','硬件','面向边缘环境的小型化、高可靠计算平台。',['边缘计算','GPU','抗震','远程管理'],'制造、零售、通信边缘','—'),
P('曙光','机架服务器','I620-G50 / I840-G30','服务器','硬件','面向通用计算和关键业务的服务器系列。',['x86','高密度','可靠性','管理平台'],'政企数据中心、科研、云','—'),P('曙光','高性能计算','ParaStor / 计算集群','AI算力','软硬一体','面向科学计算和AI的集群与并行存储方案。',['HPC','并行文件系统','高速互联','调度'],'科研、气象、仿真、AI','—'),P('长城超云','服务器','R系列 / AI服务器','服务器','硬件','国产化通用服务器与AI算力产品线。',['国产CPU','信创','GPU','BMC'],'政企信创、云、AI','—'),
P('烽火通信','交换机','FitData S 系列','交换机','硬件','面向数据中心与园区网络的交换产品。',['以太网','EVPN','MPLS','园区网络'],'运营商、政企、数据中心','—'),P('烽火通信','光传输设备','FONST 系列','光传输','硬件','面向骨干、城域和数据中心互联的光传输平台。',['OTN','DWDM','ASON','DCI'],'骨干传输、城域网、数据中心互联','—'),
P('海康威视','网络摄像机','iDS / DS-2CD 系列','视频物联','硬件+软件','覆盖通用视频监控与AI感知的网络摄像机系列。',['视频编码','AI检测','低照度','边缘智能'],'园区、交通、零售、城市治理','—'),P('海康威视','视频管理平台','HikCentral Professional','视频物联','软件','统一管理视频、门禁与物联设备的平台。',['VMS','设备管理','事件联动','开放集成'],'园区综合安防、连锁管理','—'),P('大华股份','网络摄像机','IPC-HFW / IPC-HDBW 系列','视频物联','硬件+软件','面向多场景的视频监控和智能感知设备。',['视频编码','AI检测','红外','边缘计算'],'园区、交通、零售、工厂','—'),P('大华股份','视频管理平台','DSS Professional','视频物联','软件','面向综合安防的设备、视频与事件管理平台。',['VMS','地图','事件管理','开放接口'],'园区、城市、行业安防','—'),
P('统信软件','桌面操作系统','统信 UOS 桌面版','操作系统','软件','面向桌面办公的国产操作系统。',['Linux','信创','应用生态','集中管理'],'党政办公、企业桌面','Linux'),P('统信软件','服务器操作系统','统信 UOS 服务器版','操作系统','软件','面向数据中心和云环境的服务器操作系统。',['国产CPU','容器','虚拟化','安全加固'],'服务器、云平台、关键业务','Linux'),P('麒麟软件','桌面操作系统','银河麒麟桌面操作系统 V10','操作系统','软件','面向国产化办公终端的桌面操作系统。',['Linux','国产CPU','集中管控','安全'],'党政、金融、教育办公','Linux'),P('麒麟软件','服务器操作系统','银河麒麟高级服务器操作系统 V10','操作系统','软件','面向关键业务和云数据中心的服务器操作系统。',['高可用','容器','虚拟化','安全加固'],'数据库、云平台、关键应用','Linux'),
P('达梦数据','关系型数据库','DM8','数据库','软件','国产通用关系型数据库管理系统。',['SQL','高可用','迁移工具','兼容适配'],'核心业务、政务、企业应用','—'),P('人大金仓','关系型数据库','KingbaseES V8','数据库','软件','面向关键业务的企业级关系型数据库。',['SQL','集群','容灾','迁移评估'],'政务、金融、运营商','—'),P('OceanBase','分布式数据库','OceanBase 数据库','数据库','软件','原生分布式关系型数据库。',['分布式SQL','HTAP','高可用','在线扩展'],'金融核心、互联网、运营商','—'),P('阿里云','云原生数据库','PolarDB','数据库','云服务+软件','云原生关系型数据库产品族。',['存算分离','弹性','高可用','MySQL/PostgreSQL'],'云上交易、互联网业务','—'),P('腾讯云','分布式数据库','TDSQL','数据库','云服务+软件','覆盖分布式关系型数据库与云数据库场景。',['分布式事务','弹性扩展','高可用','迁移'],'金融、政企、互联网','—'),P('东方通','应用服务器中间件','TongWeb','中间件','软件','Java EE 应用服务器中间件。',['Java EE','集群','负载均衡','信创适配'],'政务、金融、企业应用','—'),P('宝兰德','应用服务器','BES Application Server','中间件','软件','企业级 Java 应用服务器。',['Java EE','集群','监控','国产化适配'],'关键业务系统、政企应用','—'),
P('奇安信','下一代防火墙','网神 SecGate 3600','安全','硬件+软件','面向边界安全的下一代防火墙产品。',['NGFW','IPS','应用识别','威胁情报'],'互联网出口、数据中心、分支','—'),P('奇安信','终端安全','天擎终端安全管理系统','安全','软件','面向终端防护、管控和响应的安全平台。',['EPP','EDR','终端管控','漏洞管理'],'办公终端、服务器、安全运营','—'),P('启明星辰','下一代防火墙','天清汉马 USG','安全','硬件+软件','融合访问控制、入侵防御等能力的边界安全设备。',['NGFW','IPS','VPN','应用控制'],'互联网出口、数据中心边界','—'),P('绿盟科技','Web应用防火墙','WAF NX5','安全','硬件+软件','面向网站和Web应用的攻击检测与防护。',['OWASP Top 10','Bot','虚拟补丁','API防护'],'网站、互联网业务、API','—'),P('安恒信息','Web应用防火墙','明御 WAF','安全','硬件+软件','面向Web业务的应用层安全防护产品。',['Web防护','CC防护','漏洞防护','日志'],'政企门户、互联网业务','—')];
const typeColors={'交换机':'#c8ff47','路由器':'#78d7ff','安全':'#ff8f70','存储':'#bf9cff','服务器':'#ffd26f','云平台':'#80e2c4','超融合':'#80e2c4','数据库':'#ffb0d2','操作系统':'#d0d5da','无线':'#78d7ff','云桌面':'#80e2c4','网络应用':'#78d7ff','AI算力':'#ffd26f','光传输':'#78d7ff','视频物联':'#ffb56f','中间件':'#ffb0d2'};
let state={q:'',vendor:'全部',type:'全部',sort:'default',limit:18,compare:[]};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const norm=s=>(s||'').toLowerCase().replace(/\s+/g,'');const hay=p=>norm([p.vendor,p.name,p.model,p.type,p.form,p.desc,p.keys.join(' '),p.scene,p.os,p.aliases].join(' '));
const vendors=[...new Set(products.map(p=>p.vendor))],types=[...new Set(products.map(p=>p.type))];$('#productCount').textContent=products.length+'+';$('#vendorCount').textContent=vendors.length;
vendors.forEach(v=>$('#vendorFilter').insertAdjacentHTML('beforeend',`<option>${v}</option>`));types.sort().forEach(v=>$('#typeFilter').insertAdjacentHTML('beforeend',`<option>${v}</option>`));
const quick=['全部','交换机','路由器','安全','服务器','存储','超融合','数据库','操作系统','无线'];$('#quick').innerHTML=quick.map((x,i)=>`<button class="${i?'':'active'}" data-type="${x}">${x}</button>`).join('');
function filtered(){let a=products.filter(p=>(state.vendor==='全部'||p.vendor===state.vendor)&&(state.type==='全部'||p.type===state.type)&&(!state.q||hay(p).includes(norm(state.q))));if(state.sort==='vendor')a.sort((x,y)=>x.vendor.localeCompare(y.vendor,'zh-CN'));if(state.sort==='name')a.sort((x,y)=>x.name.localeCompare(y.name,'zh-CN'));return a}
function render(){const all=filtered(),rows=all.slice(0,state.limit);$('#resultCount').textContent=all.length;$('#grid').innerHTML=rows.map((p,i)=>`<article class="card" data-id="${products.indexOf(p)}" style="--i:${i}"><div class="cardtop"><span class="type" style="--tc:${typeColors[p.type]||'#ddd'}">${p.type}</span><span class="form">${p.form}</span></div><small class="vendor">${p.vendor}</small><h3>${p.name}</h3><b class="model">${p.model}</b><p>${p.desc}</p><div class="tags">${p.keys.slice(0,3).map(k=>`<span>${k}</span>`).join('')}</div><div class="cardfoot"><button class="detailBtn">查看知识点 ↗</button><label><input class="cmp" type="checkbox" ${state.compare.includes(products.indexOf(p))?'checked':''}> 加入比较</label></div></article>`).join('');$('#more').style.display=all.length>state.limit?'block':'none';$('#empty').style.display=all.length?'none':'grid';updateCompare()}
function setType(t){state.type=t;state.limit=18;$('#typeFilter').value=t;$$('#quick button').forEach(b=>b.classList.toggle('active',b.dataset.type===t));render()}
$('#quick').onclick=e=>e.target.dataset.type&&setType(e.target.dataset.type);$('#search').oninput=e=>{state.q=e.target.value;state.limit=18;render()};$('#vendorFilter').onchange=e=>{state.vendor=e.target.value;render()};$('#typeFilter').onchange=e=>setType(e.target.value);$('#sort').onchange=e=>{state.sort=e.target.value;render()};$('#more').onclick=()=>{state.limit+=18;render()};$('#clear').onclick=()=>{state={...state,q:'',vendor:'全部',type:'全部',limit:18};$('#search').value='';$('#vendorFilter').value='全部';setType('全部')};
$('#searchGo').onclick=()=>{state.q=$('#heroSearch').value;$('#search').value=state.q;location.hash='catalog';render()};$('#heroSearch').onkeydown=e=>e.key==='Enter'&&$('#searchGo').click();
$('#grid').onclick=e=>{const c=e.target.closest('.card');if(!c)return;const id=+c.dataset.id,p=products[id];if(e.target.classList.contains('cmp')){if(e.target.checked){if(state.compare.length>=4){e.target.checked=false;alert('最多同时比较 4 项');return}state.compare.push(id)}else state.compare=state.compare.filter(x=>x!==id);updateCompare();return}if(e.target.closest('.detailBtn'))openDetail(p)};
const B=(does,know,deploy,trouble)=>({does,know,deploy,trouble});
const books={
交换机:B('连接服务器、终端、AP 与上联网络，完成 VLAN 隔离、二三层转发、链路冗余和流量控制。',['VLAN/Trunk','STP/MSTP','LACP','堆叠/虚拟化','VRRP/OSPF','ACL/QoS'],['核对端口、光模块、PoE、电力和上联带宽','规划管理地址、VLAN、网关、链路聚合和生成树根','上架并配置堆叠、管理面、安全基线和时间同步','配置接入/Trunk、路由、冗余和网管','验证环路保护、主备切换、带宽和配置备份'],[['端口不通','电源/光功率/速率双工 → 接口错误包 → VLAN与端口模式 → 对端配置'],['网关不通','ARP/MAC表 → VLAN接口 → VRRP/路由表 → ACL'],['网络环路','广播与CPU → STP根桥/阻塞口 → 隔离异常链路 → 修正拓扑']]),
路由器:B('连接不同网络和广域链路，执行路由选路、VPN、NAT、QoS、分支互联和 SD-WAN。',['静态路由','OSPF/BGP','MPLS/SRv6','NAT','IPSec VPN','QoS'],['确认线路、地址、AS号、VPN和运营商参数','设计路由、备份链路、NAT和安全边界','配置管理面、接口、路由协议和认证','逐条开通主备链路与业务网段','测试收敛、时延、丢包、MTU和回退'],[['邻居不起','物理链路 → IP/掩码 → 区域/AS → 认证与ACL'],['路由有但不通','下一跳递归 → 回程路由 → NAT/ACL → MTU'],['链路质量差','接口错误/光功率 → 时延丢包 → QoS队列 → 运营商线路']]),
安全:B('在网络、终端或应用边界实施访问控制、威胁检测、攻击阻断、审计和安全响应。',['安全域/策略','对象与服务','NAT','IPS/AV','会话表','日志/威胁情报'],['梳理业务流、地址、端口和合规要求','旁路观察或小流量验证后再串联','配置路由、安全域、NAT和最小权限策略','开启检测能力并建立例外与误报流程','验证阻断、日志、告警、双机和订阅'],[['业务被阻断','策略命中/会话日志 → 路由/NAT → 安全特性阻断 → 临时例外验证'],['性能下降','CPU/内存/会话数 → 全特性吞吐 → SSL解密 → 日志负载'],['双机异常','心跳与同步 → 接口/VLAN → 抢占参数 → 会话同步']]),
无线:B('为终端提供无线接入、认证、漫游、射频优化和无线安全。',['SSID/VLAN','802.1X','CAPWAP','漫游','信道/功率','PoE'],['完成现场勘测、覆盖和容量设计','规划SSID、VLAN、认证与访客网络','部署控制器/云管、AP与PoE交换机','调优信道、功率、频宽和漫游阈值','验证覆盖、并发、漫游与弱信号区域'],[['搜不到SSID','AP供电/上线 → SSID下发 → 射频开关 → 国家码'],['认证失败','时间/凭据 → RADIUS可达 → 证书 → VLAN授权'],['卡顿掉线','RSSI/SNR → 同频干扰 → 信道利用率 → 漫游与上联']]),
服务器:B('承载操作系统、虚拟机、数据库、AI 和企业应用，提供计算、内存、本地存储与扩展资源。',['CPU/NUMA','内存通道','RAID/HBA','PCIe/GPU','BMC','固件兼容'],['核对CPU、内存、磁盘、网卡、GPU和电源','上架布线，配置带外管理与固件基线','配置BIOS、RAID、启动方式和安全项','安装系统/虚拟化及厂商驱动','压力测试、巡检、告警和备件验证'],[['无法启动','电源与告警灯 → BMC事件 → 最小化启动 → 固件'],['磁盘告警','SMART/RAID状态 → 定位槽位 → 备份 → 更换重建'],['性能异常','CPU/内存/IO → NUMA → 温度降频 → 驱动固件']]),
存储:B('为服务器和应用提供块、文件或对象数据服务，以及快照、复制、双活与备份能力。',['SAN/NAS/对象','RAID/纠删码','存储池/LUN','多路径','快照复制','RPO/RTO'],['评估容量、IOPS、时延、增长率和保护目标','设计控制器、磁盘池、前端网络和多路径','初始化阵列、存储池、主机和映射','配置快照、复制、告警和容量阈值','验证路径切换、重建、性能和恢复演练'],[['主机看不到LUN','FC zoning/iSCSI网络 → 主机映射 → LUN状态 → 多路径'],['时延升高','前端端口 → 控制器负载 → 缓存 → 热点/重建'],['容量告警','精简分配/快照 → 孤儿数据 → 扩容 → 阈值策略']]),
数据库:B('持久化和查询业务数据，提供事务、一致性、索引、备份恢复、集群与容灾。',['事务与锁','索引/执行计划','日志/WAL','主备复制','备份恢复','连接池'],['确认容量、并发、字符集、兼容性和RPO/RTO','规划实例、存储、网络、端口和账号','安装补丁，配置参数、日志和审计','迁移数据并校验对象、行数与关键SQL','完成恢复、主备切换和性能基线测试'],[['连接失败','监听/端口 → 网络/防火墙 → 账号权限 → 连接数'],['SQL变慢','等待事件 → 锁阻塞 → 执行计划/索引 → IO与统计信息'],['主备延迟','网络 → 日志产生/应用速率 → 大事务 → 备库IO']]),
操作系统:B('管理硬件资源，为应用提供进程、文件、网络、安全与运行时环境。',['进程/服务','文件系统','网络栈','权限/审计','软件包','内核参数'],['核对硬件与应用兼容清单','规划分区、网络、主机名、时间和软件源','安装系统、驱动、补丁和安全基线','部署监控、日志、备份与账号权限','完成兼容、重启恢复和基线验收'],[['启动失败','启动项/文件系统 → 内核日志 → 驱动 → 救援模式'],['服务失败','服务状态 → 端口占用 → 配置语法 → 权限依赖'],['资源耗尽','CPU/内存/磁盘/句柄 → 进程 → 日志增长 → 扩容']])};
const generic=B('为对应 IT 场景提供软硬件能力与集中管理，具体功能取决于型号、组件和授权。',['架构组成','接口与网络','高可用','监控告警','备份恢复','授权兼容'],['确认需求、拓扑、容量、兼容清单和授权','准备机房、网络、账号、版本与回退方案','完成安装、初始化和安全基线','按业务分阶段配置并联调','执行功能、性能、冗余和恢复验收'],[['无法访问','从电源、链路、地址、端口逐层检查，再核对账号与策略'],['服务异常','检查告警、日志、资源、依赖和最近变更'],['性能下降','对比基线，检查容量、时延、错误包、资源瓶颈和后台任务']]);
function getBook(p){return books[p.type]||(['云平台','超融合','云桌面'].includes(p.type)?{...generic,does:'将计算、存储、网络或桌面资源池化并统一交付，提供资源编排、高可用和集中运维。'}:generic)}
function openDetail(p){const b=getBook(p);$('#detailBody').innerHTML=`<div class="detail-kicker"><span class="type" style="--tc:${typeColors[p.type]||'#ddd'}">${p.type}</span><span>${p.form}</span></div><small>${p.vendor}</small><h2>${p.name}</h2><h3>${p.model}</h3><p class="lead">${p.desc}</p><div class="detail-tabs"><button class="active" data-tab="ability">能做什么</button><button data-tab="delivery">部署交付</button><button data-tab="trouble">问题排障</button></div><div class="tab-panel active" data-panel="ability"><section class="knowledge-block"><h4>它能做什么</h4><p>${b.does}</p></section><section class="knowledge-block"><h4>核心知识点</h4><div class="knowledge-tags">${[...new Set([...p.keys,...b.know])].map(x=>`<span>${x}</span>`).join('')}</div></section><section class="knowledge-block"><h4>典型场景</h4><p>${p.scene}</p></section></div><div class="tab-panel" data-panel="delivery"><section class="knowledge-block"><h4>部署交付步骤</h4><ol>${b.deploy.map((x,i)=>`<li><b>${String(i+1).padStart(2,'0')}</b><span>${x}</span></li>`).join('')}</ol></section><section class="knowledge-block"><h4>验收与移交</h4><p>交付拓扑、设备与授权清单、配置备份、账号移交表、测试记录、回退方案、巡检和维护手册；高可用产品必须完成真实切换验证。</p></section></div><div class="tab-panel" data-panel="trouble"><section class="knowledge-block"><h4>通用排障顺序</h4><p>确认现象与范围 → 核对最近变更 → 从物理与依赖逐层检查 → 收集日志/告警/表项 → 最小变更验证 → 恢复业务 → 复盘根因。</p></section><div class="trouble-list">${b.trouble.map(([x,y])=>`<article><b>${x}</b><p>${y}</p></article>`).join('')}</div></div><p class="detail-note">命令和界面路径因厂商、型号与版本不同；变更前请备份配置并准备回退方案。</p>`;$('#detail').showModal();$$('.detail-tabs button').forEach(btn=>btn.onclick=()=>{$$('.detail-tabs button').forEach(x=>x.classList.toggle('active',x===btn));$$('.tab-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===btn.dataset.tab))})}
function updateCompare(){$('#compareCount').textContent=state.compare.length;$('#compareBar').classList.toggle('show',state.compare.length>0);$('#compareChips').innerHTML=state.compare.map(id=>`<button data-id="${id}">${products[id].vendor} · ${products[id].model}<i>×</i></button>`).join('');$('#openCompare').disabled=state.compare.length<2}
$('#compareChips').onclick=e=>{const b=e.target.closest('button');if(b){state.compare=state.compare.filter(x=>x!==+b.dataset.id);render()}};$('#clearCompare').onclick=()=>{state.compare=[];render()};$('#openCompare').onclick=()=>{const a=state.compare.map(i=>products[i]),rows=[['厂商',...a.map(p=>p.vendor)],['产品',...a.map(p=>p.name)],['代表系列/型号',...a.map(p=>p.model)],['类别',...a.map(p=>p.type)],['形态',...a.map(p=>p.form)],['核心知识点',...a.map(p=>p.keys.join(' · '))],['典型场景',...a.map(p=>p.scene)],['系统/平台',...a.map(p=>p.os)]];$('#compareTable').innerHTML=`<table>${rows.map((r,i)=>`<tr>${r.map((x,j)=>`<${i===0||j===0?'th':'td'}>${x}</${i===0||j===0?'th':'td'}>`).join('')}</tr>`).join('')}</table><p class="compare-note">比较结果用于建立产品认知；涉及性能、端口、授权和兼容性时，请以具体型号最新数据表为准。</p>`;$('#compare').showModal()};
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.onclick=e=>{if(e.target===d)d.close()});
const capability={网络:['华为','新华三 H3C','锐捷网络','中兴通讯','烽火通信'],安全:['深信服','奇安信','启明星辰','绿盟科技','安恒信息','华为','新华三 H3C'],计算与存储:['浪潮信息','联想','华为','新华三 H3C','曙光','长城超云'],基础软件:['统信软件','麒麟软件','达梦数据','人大金仓','OceanBase','东方通','宝兰德'],云与数据:['阿里云','腾讯云','华为','深信服','中兴通讯'],视频物联:['海康威视','大华股份']};$('#vendorMap').innerHTML=Object.entries(capability).map(([k,v],i)=>`<article><span>0${i+1}</span><h3>${k}</h3><div>${v.map(x=>`<button data-vendor="${x}">${x}</button>`).join('')}</div></article>`).join('');$('#vendorMap').onclick=e=>{if(e.target.dataset.vendor){state.vendor=e.target.dataset.vendor;$('#vendorFilter').value=state.vendor;location.hash='catalog';render()}};
$('#theme').onclick=()=>{document.documentElement.classList.toggle('dark');localStorage.theme=document.documentElement.classList.contains('dark')?'dark':'light'};if(localStorage.theme==='dark')document.documentElement.classList.add('dark');render();
